import { Mediastack } from "../models/mediastackNews";

export const news: Mediastack[] = [
  {
      "author": "Associated Press",
      "title": "’Malcolm in the Middle’ star Frankie Muniz lands full-time NASCAR ride in 2025",
      "description": "Former Malcolm in the Middle star Frankie Muniz is set to continue his NASCAR career with a full-time ride in the Truck Series for 2025. Muniz will make the jump from part-time racer to a full slate in the No. 33 Ford for Reaume Brothers Racing. He made two starts for Reaume Brothers this season in [&#8230;]",
      "url": "https://torontosun.com/sports/auto-racing/muniz-lands-full-time-nascar-ride",
      "source": "torontosun",
      "image": null,
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:54+00:00"
    },
    {
      "author": "The Associated Press",
      "title": "McDonald’s tries to reassure customers after deadly E. coli outbreak",
      "description": "The company has removed the Quarter Pounder from its menu in 10 states where illnesses were reported.",
      "url": "https://www.presstelegram.com/2024/10/23/mcdonalds-tries-to-reassure-customers-after-deadly-e-coli-outbreak/",
      "source": "Press-Telegram",
      "image": "https://www.presstelegram.com/wp-content/uploads/2024/10/McDonalds_86512.jpg?w=1400px&strip=all",
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:48+00:00"
    },
    {
      "author": "The Associated Press",
      "title": "McDonald’s tries to reassure customers after deadly E. coli outbreak",
      "description": "The company has removed the Quarter Pounder from its menu in 10 states where illnesses were reported.",
      "url": "https://www.sgvtribune.com/2024/10/23/mcdonalds-tries-to-reassure-customers-after-deadly-e-coli-outbreak/",
      "source": "sgvtribune",
      "image": "https://www.sgvtribune.com/wp-content/uploads/2024/10/McDonalds_86512.jpg?w=1400px&strip=all",
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:48+00:00"
    },
    {
      "author": "The Associated Press",
      "title": "McDonald’s tries to reassure customers after deadly E. coli outbreak",
      "description": "The company has removed the Quarter Pounder from its menu in 10 states where illnesses were reported.",
      "url": "https://www.ocregister.com/2024/10/23/mcdonalds-tries-to-reassure-customers-after-deadly-e-coli-outbreak/",
      "source": "ocregister",
      "image": "https://www.ocregister.com/wp-content/uploads/2024/10/McDonalds_86512.jpg?w=1400px&strip=all",
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:48+00:00"
    },
    {
      "author": null,
      "title": "Diageo India’s net profit falls to ₹341 crore amid muted demand environment",
      "description": "Diageo India’s consolidated net profit for last quarter was ₹485 crore",
      "url": "https://www.thehindubusinessline.com/companies/diageo-indias-net-profit-falls-to-341-crore-amid-muted-demand-environment/article68788078.ece",
      "source": "Business Line",
      "image": "https://bl-i.thgim.com/public/incoming/mjrhsn/article68788314.ece/alternates/LANDSCAPE_1200/IMG_FILE_PHOTO__A_sign_i_2_1_LJD3PLMO.jpg",
      "category": "business",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:45+00:00"
    },
    {
      "author": "MiMorelia.com",
      "title": "VIRAL: marihuana queda regada en calle de Pátzcuaro y \"Tazo dorado\" busca su dosis [Video]",
      "description": "VIRAL: marihuana queda regada en calle de Pátzcuaro y \"Tazo dorado\" busca su dosis [Video]",
      "url": "https://mimorelia.com/noticias/entretenimiento/viral-marihuana-queda-regada-en-calle-de-pátzcuaro-y-tazo-dorado-busca-su-dosis-video",
      "source": "mimorelia",
      "image": null,
      "category": "general",
      "language": "es",
      "country": "es",
      "published_at": "2024-10-23T16:35:45+00:00"
    },
    {
      "author": null,
      "title": "News24 | Thursday's weather: Hot temperatures expected across several regions",
      "description": "Extremely high fire danger is expected in Hantam municipality of the Western Cape and the central and south-eastern parts of the Northern Cape, according to the South African Weather Service.",
      "url": "https://www.news24.com/news24/southafrica/news/thursdays-weather-hot-temperatures-expected-across-several-regions-20241023",
      "source": "News24",
      "image": "https://cdn.24.co.za/files/Cms/General/d/12336/a2cd693c37c1495587c78ae7f31c0715.jpg",
      "category": "general",
      "language": "en",
      "country": "za",
      "published_at": "2024-10-23T16:35:40+00:00"
    },
    {
      "author": null,
      "title": "Uber auto, moto services to drive ₹36,000 cr in economic activity in 2024: Report",
      "description": "Uber auto, moto services to drive ₹36,000 cr in economic activity in 2024: Report",
      "url": "https://www.thehindubusinessline.com/companies/uber-auto-moto-services-to-drive-36000-cr-in-economic-activity-in-2024-report/article68788079.ece",
      "source": "Business Line",
      "image": "https://bl-i.thgim.com/public/incoming/af0zid/article68788648.ece/alternates/LANDSCAPE_1200/Auto_02.jpg",
      "category": "business",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:32+00:00"
    },
    {
      "author": "Bettina Makalintal",
      "title": "McDonald’s Quarter Pounders Sicken Dozens in E. coli Outbreak",
      "description": "The McDonald’s Quarter Pounder is at the center of a new E. coli outbreak. | Scott Olson/Getty Images It continues to be a bleak week for McDonald’s After making headlines earlier this week following presidential candidate and former president Donald Trump’s stunt cosplaying as a service worker, McDonald’s is back in the news again, this time for an even bleaker reason: The CDC announced yesterday that it’s investigating an E. coli outbreak linked to the company’s Quarter Pounders. As of this writing, the CDC reports 49 cases in 10 states, including one death and 10 hospitalizations...",
      "url": "https://www.eater.com/24277727/mcdonalds-quarter-pounder-e-coli-outbreak-explained",
      "source": "eater",
      "image": null,
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:35:32+00:00"
    },
    {
      "author": "info@futbolecuador.com",
      "title": "Luis Enrique, frustrado por el 'injusto' empate del PSG ante el PSV(VIDEO)",
      "description": "El entrenador del Par&iacute;s Saint-Germain, Luis Enrique, expres&oacute; su frustraci&oacute;n tras el empate 2-2 contra el PSV Eindhoven en la tercera jornada de la fase de liga de la UEFA Champions League.",
      "url": "https://www.futbolecuador.com/site/noticia/el-tecnico-de-willian-pacho-lamento-el-resultado-tras-el-empate-en-la-champions-league-contra-el-psv-asegurando-que-su-equipo-fue-superior-durante-el-partido/168958?fromt=yes",
      "source": "futbolecuador.com",
      "image": "https://www.futbolecuador.com/imagenes/images/thumb640/67d49f0834821d28a55b53e31d6d3b3c.jpg",
      "category": "general",
      "language": "es",
      "country": "ec",
      "published_at": "2024-10-23T16:35:25+00:00"
    },
    {
      "author": "Giuseppe Cozzolino",
      "title": "Rubano castagne in un fondo agricolo in Irpinia, arrestati tre giovani napoletani",
      "description": "Sorpresi a rubare castagne in un castagneto: tre napoletani arrestati dai carabinieri. Obbligo di firma per tutti, proposto anche il foglio di via obbligatorio.Continua a leggere",
      "url": "https://www.fanpage.it/napoli/rubano-castagne-in-un-fondo-agricolo-in-irpinia-arrestati-tre-giovani-napoletani/",
      "source": "Fanpage",
      "image": null,
      "category": "general",
      "language": "it",
      "country": "it",
      "published_at": "2024-10-23T16:35:19+00:00"
    },
    {
      "author": "HDblog.it",
      "title": "iPhone 16, Samsung Evo Select, Smart TV LG e altro | Le 5 migliori offerte di oggi",
      "description": "Ecco le 5 migliori offerte di oggi, 23 ottobre, su Amazon ed eBay.",
      "url": "https://www.hdblog.it/ebay/offerte/n597130/migliori-5-offerte-oggi-amazon-ebay/",
      "source": "hdblog",
      "image": null,
      "category": "general",
      "language": "it",
      "country": "it",
      "published_at": "2024-10-23T16:35:00+00:00"
    },
    {
      "author": null,
      "title": "'Black Swan' ballerina Ashley Benefield reenacts fatal shooting of 'abusive' husband in shocking photos",
      "description": "Ashley Benefield, 33, who was found guilty of manslaughter after fatally shooting her husband, participated in a reenactment of the killing.",
      "url": "https://www.dailymail.co.uk/news/article-13987429/black-swan-ballerina-ashley-benefield-reenacts-shooting-husband-court-photos.html?ns_mchannel=rss&ito=1490&ns_campaign=1490",
      "source": "dailymail",
      "image": "https://i.dailymail.co.uk/1s/2024/10/22/21/91156101-0-image-m-83_1729629360688.jpg",
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:58+00:00"
    },
    {
      "author": "Page Six Video",
      "title": "Harry Hamlin dishes on ‘his ‘Famous’ sauce recipe and time spent ‘In The Kitchen’",
      "description": "Harry Hamlin, aka Mrs. Lisa Rinna stopped by the Page Six studios and sat with Astra to get a little &#8216;saucy&#8217; as he unveiled his new line of mouth-watering, unforgettable Rosemary red wine sauces. Harry&#8217;s Famous Sauce has become a Sunday family tradition that the actor is now sharing with the world. A large portion...",
      "url": "https://pagesix.com/video/harry-hamlin-dishes-on-his-famous-sauce-recipe-and-time-spent-in-the-kitchen/",
      "source": "Post",
      "image": "https://pagesix.com/wp-content%2Fuploads%2Fsites%2F3%2F2024%2F10%2FWP_47b2f4.jpg?quality%3D90%26strip%3Dall",
      "category": "general",
      "language": "en",
      "country": "zm",
      "published_at": "2024-10-23T16:34:58+00:00"
    },
    {
      "author": "Alessio Baronci",
      "title": "We Live in Time, di John Crowley",
      "description": "La malattia è quasi l’interferenza di una rom com sulla prova più grande di una coppia. Ma resta ottima la prova di Andrew Garfield e Florence Pugh. RoFF19. Grand PublicL'articolo We Live in Time, di John Crowley proviene da SentieriSelvaggi.",
      "url": "https://www.sentieriselvaggi.it/we-live-in-time-di-john-crowley/",
      "source": "sentieriselvaggi",
      "image": null,
      "category": "general",
      "language": "it",
      "country": "it",
      "published_at": "2024-10-23T16:34:56+00:00"
    },
    {
      "author": "Dave DeCamp",
      "title": "Two US Troops Injured During Raid Against ISIS in Iraq",
      "description": "Two US troops were wounded in a raid against ISIS in central Iraq that was conducted with Iraqi government forces, US Central Command said on Wednesday. CENTCOM claimed seven ISIS fighters were killed in the raid, which it said was led by Iraqi forces. &#8220;During the Iraqi-led operation, two US military personnel were wounded while &#8230; Continue reading \"Two US Troops Injured During Raid Against ISIS in Iraq\"",
      "url": "https://news.antiwar.com/2024/10/23/two-us-troops-injured-during-raid-against-isis-in-iraq/",
      "source": "antiwar",
      "image": null,
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:47+00:00"
    },
    {
      "author": "Admin",
      "title": "PNN hizo reconocimiento especial a la Reserva Natural de la sociedad civil de Valledupar",
      "description": "Experiencia de Reserva Natural de la Sociedad Civil de Valledupar, presente en la COP 16 Se trata de la primeraThe post PNN hizo reconocimiento especial a la Reserva Natural de la sociedad civil de Valledupar first appeared on EL PAÍS VALLENATO.",
      "url": "https://www.elpaisvallenato.com/2024/10/23/pnn-hizo-reconocimiento-especial-a-la-reserva-natural-de-la-sociedad-civil-de-valledupar/?utm_source=rss&utm_medium=rss&utm_campaign=pnn-hizo-reconocimiento-especial-a-la-reserva-natural-de-la-sociedad-civil-de-valledupar",
      "source": "elpaisvallenato",
      "image": null,
      "category": "general",
      "language": "es",
      "country": "es",
      "published_at": "2024-10-23T16:34:46+00:00"
    },
    {
      "author": "Peter Fitzpatrick",
      "title": "Barcelona vs Bayern Munich LIVE! Champions League match stream, latest team news, lineups, TV, prediction",
      "description": "Hansi Flick looking for revenge against former club",
      "url": "https://www.standard.co.uk/sport/football/fc-barcelona-vs-bayern-munich-live-stream-champions-league-2024-latest-score-result-watch-tv-team-news-b1189663.html",
      "source": "thisislondon",
      "image": "https://static.standard.co.uk/s3fs-public/thumbnails/image/2020/08/09/11/barcelonabayern090820b.png?width=1200&auto=webp",
      "category": "general",
      "language": "en",
      "country": "uk",
      "published_at": "2024-10-23T16:34:43+00:00"
    },
    {
      "author": "Trevor",
      "title": "SMPD Needs Assistance Locating Assault Suspect",
      "description": "SANTA MONICA—On Tuesday, October 22, Lt. Erika Aklufi of the Santa Monica Police Department informed Canyon News via email that they are seeking the public’s help in locating a suspect who assaulted an individual. Authorities have released video of the suspect to the public. The incident transpired back on Sunday, September 22 at 12:35 a.m. [&#8230;]The post SMPD Needs Assistance Locating Assault Suspect appeared first on Canyon News.",
      "url": "https://www.canyon-news.com/smpd-needs-assistance-locating-assault-suspect/187728",
      "source": "canyon-news",
      "image": "https://www.santamonica.gov/media/Police/suspects/SMPD%20Community%20Assistance%20-%20Sept%2022%20Incident.mp4",
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:40+00:00"
    },
    {
      "author": "Redazione TRC",
      "title": "Berlinguer a Civitavecchia. Un ricordo",
      "description": "di FLAVIO MARTINO Alla vigilia della presentazione del libro &#8220;Opposizione, l’ultima battaglia di Enrico Berlinguer&#8221;, scritto da Luca Telese, vale forse la pena di ricordare il rapporto tra il più amato segretario del Pci e Civitavecchia, avvalendoci anche delle bellissime foto dell&#8217;amico Gianni Tassi. In città Berlinguer aveva un&#8217;antica amicizia con Bruno Bergantini, popolare tassista, [&#8230;]",
      "url": "https://trcgiornale.it/berlinguer-a-civitavecchia-un-ricordo/",
      "source": "trcgiornale",
      "image": null,
      "category": "general",
      "language": "it",
      "country": "it",
      "published_at": "2024-10-23T16:34:31+00:00"
    },
    {
      "author": "jennastanley",
      "title": "Whippets take win over Leake Central ready for.  Houston",
      "description": "Whippets take win over Leake Central ready for.&nbsp; HoustonjennastanleyWed, 10/23/2024 - 11:34 AM",
      "url": "https://www.starherald.net/local-content-local-sports/whippets-take-win-over-leake-central-ready-houston",
      "source": "starherald",
      "image": null,
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:26+00:00"
    },
    {
      "author": "BusinessWorld",
      "title": "PCCI issues job, investment wish list",
      "description": "PRESIDENT Ferdinand R. Marcos, Jr. should identify barriers to business operations, develop an infrastructure master plan, enact a comprehensive investment bill and digitize local government services to generate more investments and jobs, according to the Philippine Chamber of Commerce and Industry (PCCI).",
      "url": "https://www.bworldonline.com/top-stories/2024/10/24/630281/pcci-issues-job-investment-wish-list/",
      "source": "Business World",
      "image": "https://www.bworldonline.com/wp-content/uploads/2024/10/Job-fair-applicant-300x200.jpg",
      "category": "business",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:26+00:00"
    },
    {
      "author": "Jon Duarte",
      "title": "Shelton Benjamin: «Bobby Lashley sería una victoria para AEW»",
      "description": "Shelton Benjamin comenta la posibilidad de que Bobby Lashley se una también a AEW.",
      "url": "https://superluchas.com/shelton-benjamin-bobby-lashley-seria-una-victoria-para-aew/",
      "source": "superluchas",
      "image": null,
      "category": "general",
      "language": "es",
      "country": "es",
      "published_at": "2024-10-23T16:34:26+00:00"
    },
    {
      "author": "New York Post Video",
      "title": "Watch Live: JD Vance holds rally in Las Vegas",
      "description": "Republican vice presidential nominee JD Vance is scheduled to speak to supporters at 1 ET in Las Vegas, the first of two campaign stops today in Nevada for Senator Vance.",
      "url": "https://nypost.com/video/watch-live-jd-vance-holds-rally-in-las-vegas/",
      "source": "Post",
      "image": "https://nypost.com/wp-content%2Fuploads%2Fsites%2F2%2F2024%2F10%2Fvance.png",
      "category": "general",
      "language": "en",
      "country": "zm",
      "published_at": "2024-10-23T16:34:23+00:00"
    },
    {
      "author": "Curtis Jackson",
      "title": "Forest Service to burn slash piles in Ashton-Island Park Ranger District",
      "description": "The following is a news release from Caribou-Targhee National Forest. FREMONT COUNTY, Idaho (Caribou-Targhee National Forest News Release) – Caribou-Targhee fire personnel plan to implement controlled burns of slash piles in various locations within the Ashton/Island Park District, commencing as early as October 28, 2024. These burns are expected to continue through the end of December,",
      "url": "https://localnews8.com/news/2024/10/23/forest-service-to-burn-slash-piles-in-ashton-island-park-ranger-district/",
      "source": "localnews8",
      "image": null,
      "category": "general",
      "language": "en",
      "country": "us",
      "published_at": "2024-10-23T16:34:22+00:00"
    }
]
